### ISSUE TITLE
[Notes] Provisioning Profile 에러 해결하기!!

### ISSUE THREAD

**Issue by Rookie0031** [ECube-Reboot/LiveOn-Reborn-iOS#27]
# Provisioning Profile
 개인 기기로 앱을 실행하려고 하면 프로비저닝 프로파일 에러를 만나게 된다. Xcode를 통해서 앱을 실행하면, 이 앱이 애플의 기기에서 돌아가도 괜찮은지, 합법적인 앱인지 먼저 애플에서 인증을 하고 빌드 명령을 내리는데. 그 때 애플의 빌드 승인을 받기 위해 개발자가 보내주는 파일이 프로비저닝 프로파일이다.
 프로비저닝 프로파일은 다음 세 가지를 포함하는 문서이다. 

1. Certificate : 애플에 등록된 개발자임을 인증할 수 있는 인증서 (개발자 신청 후 받을 수 있다)
2. Device Information : 앱을 실행하려는 기기의 정보
3. App ID: 앱을 식별할 수 있는 문자열 (제품의 시리얼 넘버 정도로 이해하면 된다)

## Provisioning Profile 생성하기
애플 개발자 계정 페이지로 들어가면 프로비저닝 프로파일을 생성할 수 있다 ( 프로파일 만드는 방법은 그때 옛날에 누가 앱출시 관련 글을 카톡방에 올려줬는데 그거 참고하면 됨)
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/103009135/181905805-30cc9c3e-ca0a-4188-842b-7ca12c0a73b0.png">

프로비저닝 프로파일은 certificate, device info, app ID를 담는 문서라고 했다. 그니까 이 문서를 만들려면 LiveOn 앱의 app ID가 뭔지 알아야한다. 근데 내가 만들고 있는 앱 프로젝트가 전부 등록되어서 리스트로 뜨는데 이중에 뭐가 LiveON의 app ID가 뭔지 모르겠다. 아마 예전에 삽질하면서 많이 생성해놓은거같은데... 식별가능한 형태가 아니라 새로 만들어보기로 했다. 

## App ID 등록 
<img width="2240" alt="image" src="https://user-images.githubusercontent.com/103009135/181905856-0378a52f-a10d-47e0-bb63-6dc8810f9987.png">

앱을 식별하는 app ID는 맨앞에 이상한 영어문자가 붙고 그 뒤에 bundleIdentifier(내가 설정) 를 붙이는 방식이다.

## Bundle Identifier 설정
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/103009135/181906001-677dc3c6-158f-4ed7-aa21-8df74745e39e.png">
## 새로만든 App ID로 Provisioning profile 만들기
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/103009135/181909240-e45ecb8f-5562-489e-b154-a1b60b92a2c1.png">
#### 이제 이거로 provisioning profile 만들기를 다시 진행하면 된다

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/103009135/181909307-40c462dc-6fc6-4364-b638-7fe166ade8ee.png">

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/103009135/181909341-ed4b2dad-bd28-4505-8f02-9c60b185d028.png">

절차대로 진행하고 다운받으면 다음과 같다
<img width="805" alt="image" src="https://user-images.githubusercontent.com/103009135/181909402-55912645-32fa-4dbe-8d62-a4b44ac98cf6.png">

## 빌드 성공
추후 다운받은 프로비저닝 파일을 넣고 실행하면 빌드가 된다
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/103009135/181909705-1cd4a21e-d61a-4ebe-87e7-4d47d758b375.png">

## Reference
https://hyunndyblog.tistory.com/150
https://eunjin3786.tistory.com/373

## 결론
각자의 디바이스에 맞게 provisioning file을 만들고, 올바른 bundle identifier를 넣고 돌리면됨

**Comment by italsehf** [comment]
Provisioning Profile 어려워서 이해하기 힘들었을텐데 친절하게 적어줘서 thanx, bro 😄

하지만 요약해서 말하자면 이렇게 개개인이 Provisioning Profile을 만들어서 빌드하게 되면 
한명이 PR을 날리고 머지한 다음에 Pull을 당기게 되면 지금 본인이 사용하고 있던 Provisioning Profile하고
Pull 당겨온 Provisioning Profile 다르기 때문에 또다시 Provisioning Profile 에러가 발생함ㅜㅜ

그래서 이거에 대한 해결방법은 원래 팀 협업을 하면 팀 계정을 파서 진행해야 하지만
우리는 지금 개인 개발자 계정을 갖고 진행하고 있고 추가적으로  App Store Connect에 등록된 번들 ID랑 
Xcode 프로젝트 파일의 번들 ID랑 똑같아야지 나중에 문제가 안 생기기에 

=> 내 iOS Development 개인 키와 내가 만든 Provisioning Profile 파일을 팀원들에게 나눠줘서
먼저 iOS Development Certificate을 각자 맥북에 설치를 한 다음에 Xcode에서
Auto 어쩌구 저쩌구를 끈 다음에 Import Profile에서 내가 준 Provisioning Profile 파일을 
넣게 되면 이제 Provisioning Profile 에러는 더 이상 뜨지 않게 됩니다 ~!

혹시라도 문제가 생길 수도 있어서 혹시 모르니까 화요일 정기 회의 시간에 두 개의 파일을 공유해서
문제없이 빌드가 되는 지 확인할 예정입니다 ^^
