### ISSUE TITLE
[HELP] Calendar 다가오는 기념일 Post 에러

### ISSUE THREAD

**Issue by Rookie0031** [ECube-Reboot/LiveOn-Reborn-iOS#50]
## 상황 설명
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/103009135/187190446-465e9e30-6613-4d1c-84ea-9dcb01fc8fca.png">

이상한점은 클라쪽에서 post하고 response로 status 400을 받지만 success 케이스로 분류되어서 작동된다는것임

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/103009135/187190530-7d29beee-0e53-4e6f-8380-34e70ce01d66.png">

## 추정
검색해보니 parameter 전달을 제대로 안해서 그렇다고 함
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/103009135/187193900-d32123f4-a675-49b1-80b9-79f9ae198317.png">

## 해결
서버 측에서 정해놓은 스트링 타입으로 보내야햇엇다 (2022-08-29 같은 타입)
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/103009135/187193656-e29ab50e-fc51-4c72-b91e-e76af5821326.png">

근데 status code 400임에도 success 케이스로 분류되는 것은 왠지 모르겟다

**Comment by italsehf** [comment]
혼또니 아리가또🥰
